# Generated by Django 4.1.7 on 2023-06-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
