# Generated by Django 4.1.7 on 2023-06-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_author_alter_feedback_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='alles',
            field=models.BooleanField(blank=True, default=True, verbose_name='Показывать всем '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Тема сообщения'),
        ),
    ]
