# Generated by Django 4.1.7 on 2023-06-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedback_alles_alter_feedback_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date',
        ),
    ]
