# Generated by Django 4.1.7 on 2023-06-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_remove_feedback_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='alles',
        ),
    ]
