# Generated by Django 4.1.7 on 2023-07-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_feedback_mail_feedback_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='phone',
        ),
    ]
