# Generated by Django 4.1.7 on 2023-04-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acad',
            name='image',
            field=models.ImageField(upload_to='rezume/media/'),
        ),
    ]
