# Generated by Django 4.1.7 on 2023-05-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezume', '0002_alter_acad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezume',
            name='description',
            field=models.TextField(),
        ),
    ]
