# Generated by Django 4.1.7 on 2023-06-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezume', '0004_alter_acad_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('drawing', models.FileField(blank=True, upload_to='rezume/media/')),
                ('dr_spec', models.FileField(blank=True, upload_to='rezume/media/')),
                ('dr_model', models.FileField(blank=True, upload_to='rezume/media/')),
            ],
        ),
    ]
