# Generated by Django 4.1.7 on 2023-06-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezume', '0005_arbeit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeit',
            name='dr_model',
            field=models.FileField(blank=True, upload_to='arbeit/media/'),
        ),
        migrations.AlterField(
            model_name='arbeit',
            name='dr_spec',
            field=models.FileField(blank=True, upload_to='arbeit/media/'),
        ),
        migrations.AlterField(
            model_name='arbeit',
            name='drawing',
            field=models.FileField(blank=True, upload_to='arbeit/media/'),
        ),
    ]
