# Generated by Django 4.1.7 on 2023-06-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezume', '0006_alter_arbeit_dr_model_alter_arbeit_dr_spec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proggg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
