# Generated by Django 4.1.7 on 2023-06-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezume', '0007_proggg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeit',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='arbeit',
            name='dr_model',
            field=models.FileField(blank=True, upload_to='arbeit/media/', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='arbeit',
            name='dr_spec',
            field=models.FileField(blank=True, upload_to='arbeit/media/', verbose_name='Спецификация'),
        ),
        migrations.AlterField(
            model_name='arbeit',
            name='drawing',
            field=models.FileField(blank=True, upload_to='arbeit/media/', verbose_name='Чертеж'),
        ),
        migrations.AlterField(
            model_name='arbeit',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='proggg',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание программы'),
        ),
        migrations.AlterField(
            model_name='proggg',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='proggg',
            name='url',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='rezume',
            name='date1',
            field=models.CharField(max_length=20, verbose_name='Дата1'),
        ),
        migrations.AlterField(
            model_name='rezume',
            name='date2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Дата2'),
        ),
        migrations.AlterField(
            model_name='rezume',
            name='description',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='rezume',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Место работы'),
        ),
    ]
