
from django.db import models

class Detal(models.Model):
    idcopybook = models.IntegerField()
    number = models.CharField(max_length=25)
    title = models.CharField(max_length=127)
    a1 = models.DecimalField(max_digits=7, decimal_places=3, blank = True, null = True)
    a2 = models.DecimalField(max_digits=7, decimal_places=3, blank = True, null = True)
    a3 = models.DecimalField(max_digits=7, decimal_places=3, blank = True, null = True)
    a4 = models.DecimalField(max_digits=7, decimal_places=3, blank = True, null = True)
    a5 = models.DecimalField(max_digits=7, decimal_places=3, blank = True, null = True)
    a6 = models.DecimalField(max_digits=7, decimal_places=3, blank = True, null = True)
    a8 = models.DecimalField(max_digits=7, decimal_places=3, blank = True, null = True)
    a9 = models.DecimalField(max_digits=7, decimal_places=3, blank = True, null = True)
    a10 = models.DecimalField(max_digits=7, decimal_places=3, blank = True, null = True)
    a11 = models.DecimalField(max_digits=7, decimal_places=3, blank = True, null = True)
    a12 = models.DecimalField(max_digits=7, decimal_places=3, blank = True, null = True)
    a13 = models.DecimalField(max_digits=7, decimal_places=3, blank = True, null = True)
    a14 = models.DecimalField(max_digits=7, decimal_places=3, blank = True, null = True)
    a15 = models.DecimalField(max_digits=7, decimal_places=3, blank = True, null = True)
    a16 = models.DecimalField(max_digits=7, decimal_places=3, blank = True, null = True)
    a17 = models.DecimalField(max_digits=7, decimal_places=3, blank = True, null = True)
    a18 = models.DecimalField(max_digits=7, decimal_places=3, blank = True, null = True)
    t19 = models.CharField(max_length=127, blank=True, null=True)
    t20 = models.CharField(max_length=127, blank=True, null=True)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

class Copybook(models.Model):
    usr=models.CharField(max_length=127)
    title=models.CharField(max_length=127)
    url= models.URLField(blank=True)
    n1=models.CharField(max_length=8, blank=True, null=True)
    n2=models.CharField(max_length=8, blank=True, null=True)
    n3=models.CharField(max_length=8, blank=True, null=True)
    n4=models.CharField(max_length=8, blank=True, null=True)
    n5=models.CharField(max_length=8, blank=True, null=True)
    n6=models.CharField(max_length=8, blank=True, null=True)
    n7=models.CharField(max_length=8, blank=True, null=True)
    n8=models.CharField(max_length=8, blank=True, null=True)
    n8=models.CharField(max_length=8, blank=True, null=True)
    n8=models.CharField(max_length=8, blank=True, null=True)
    n8=models.CharField(max_length=8, blank=True, null=True)
    n9=models.CharField(max_length=8, blank=True, null=True)
    n10=models.CharField(max_length=8, blank=True, null=True)
    n11=models.CharField(max_length=8, blank=True, null=True)
    n12=models.CharField(max_length=8, blank=True, null=True)
    n13=models.CharField(max_length=8, blank=True, null=True)
    n14=models.CharField(max_length=8, blank=True, null=True)
    n15=models.CharField(max_length=8, blank=True, null=True)
    n16=models.CharField(max_length=8, blank=True, null=True)
    n17=models.CharField(max_length=8, blank=True, null=True)
    n18=models.CharField(max_length=8, blank=True, null=True)
    n19=models.CharField(max_length=8, blank=True, null=True)
    n20=models.CharField(max_length=8, blank=True, null=True)

class Aonn(models.Model):
    idcopybook = models.IntegerField()
    o1=models.BooleanField(blank=True, null=True)
    o2=models.BooleanField(blank=True, null=True)
    o3=models.BooleanField(blank=True, null=True)
    o4=models.BooleanField(blank=True, null=True)
    o5=models.BooleanField(blank=True, null=True)
    o6=models.BooleanField(blank=True, null=True)
    o7=models.BooleanField(blank=True, null=True)
    o8=models.BooleanField(blank=True, null=True)
    o9=models.BooleanField(blank=True, null=True)
    o10=models.BooleanField(blank=True, null=True)
    o11=models.BooleanField(blank=True, null=True)
    o12=models.BooleanField(blank=True, null=True)
    o13=models.BooleanField(blank=True, null=True)
    o14=models.BooleanField(blank=True, null=True)
    o15=models.BooleanField(blank=True, null=True)
    o16=models.BooleanField(blank=True, null=True)
    o17=models.BooleanField(blank=True, null=True)
    o18=models.BooleanField(blank=True, null=True)
    o19=models.BooleanField(blank=True, null=True)
    o20=models.BooleanField(blank=True, null=True)

class Alist(models.Model):
    idcopybook = models.IntegerField()
    l1=models.BooleanField(blank=True, null=True)
    l2=models.BooleanField(blank=True, null=True)
    l3=models.BooleanField(blank=True, null=True)
    l4=models.BooleanField(blank=True, null=True)
    l5=models.BooleanField(blank=True, null=True)
    l6=models.BooleanField(blank=True, null=True)
    l7=models.BooleanField(blank=True, null=True)
    l8=models.BooleanField(blank=True, null=True)
    l9=models.BooleanField(blank=True, null=True)
    l10=models.BooleanField(blank=True, null=True)
    l11=models.BooleanField(blank=True, null=True)
    l12=models.BooleanField(blank=True, null=True)
    l13=models.BooleanField(blank=True, null=True)
    l14=models.BooleanField(blank=True, null=True)
    l15=models.BooleanField(blank=True, null=True)
    l16=models.BooleanField(blank=True, null=True)
    l17=models.BooleanField(blank=True, null=True)
    l18=models.BooleanField(blank=True, null=True)
    l19=models.BooleanField(blank=True, null=True)
    l20=models.BooleanField(blank=True, null=True)



